---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhooksclient
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: webhooksclient
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: webhooksclient
    spec:
      containers:
      - name: webhooksclient
        image: eshop/webhooksclient:eshop
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        - containerPort: 8443
        envFrom:
        - configMapRef:
            name: webhooksclient-env
      terminationGracePeriodSeconds: 180