resources:
- deployment.yml
- service.yml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: basket-api-env
  literals:
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES=true
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES=true
    - Identity__Url=http://identity-api:8080
    - ASPNETCORE_URLS=http://+:8080

secretGenerator:
- name: basket-api-secrets
  envs:
  - .basket-api.secrets
